# Part - 1

In [1]:
# Import the required packages
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import pandas as pd

In [2]:
A = array([[2.5,2.4],
           [0.5,0.7],
           [2.2,2.9],
           [1.9,2.2],
           [3.1,3.0],
           [2.3,2.7],
           [2,1.6],
           [1,1.1],
           [1.5,1.6],
           [1.1,0.9]])

In [3]:
print(A)

[[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]


In [4]:
M = mean(A.T, axis=1)
print(M)

[1.81 1.91]


In [5]:
C = A - M
print(C)

[[ 0.69  0.49]
 [-1.31 -1.21]
 [ 0.39  0.99]
 [ 0.09  0.29]
 [ 1.29  1.09]
 [ 0.49  0.79]
 [ 0.19 -0.31]
 [-0.81 -0.81]
 [-0.31 -0.31]
 [-0.71 -1.01]]


In [6]:
V = cov(C.T)
print(V)

[[0.61655556 0.61544444]
 [0.61544444 0.71655556]]


In [7]:
values, vectors = eig(V)
print(vectors)
print(values)

[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]
[0.0490834  1.28402771]


In [8]:
P = vectors.T.dot(C.T)
print(P.T)

[[-0.17511531 -0.82797019]
 [ 0.14285723  1.77758033]
 [ 0.38437499 -0.99219749]
 [ 0.13041721 -0.27421042]
 [-0.20949846 -1.67580142]
 [ 0.17528244 -0.9129491 ]
 [-0.3498247   0.09910944]
 [ 0.04641726  1.14457216]
 [ 0.01776463  0.43804614]
 [-0.16267529  1.22382056]]


In [9]:
from sklearn.decomposition import PCA

pca = PCA(2)
pca.fit_transform(A)
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]
[1.28402771 0.0490834 ]
[[-0.82797019 -0.17511531]
 [ 1.77758033  0.14285723]
 [-0.99219749  0.38437499]
 [-0.27421042  0.13041721]
 [-1.67580142 -0.20949846]
 [-0.9129491   0.17528244]
 [ 0.09910944 -0.3498247 ]
 [ 1.14457216  0.04641726]
 [ 0.43804614  0.01776463]
 [ 1.22382056 -0.16267529]]


# Part - 2

In [10]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [11]:
df = pd.read_csv('D:/DataSets/archive (19)/amsPred-Sheet1.csv')
df.head()

Attendance  MSE  HRS  ESE
0          70   10   17   42
1          92    7   20   39
2          67    3   18   32
3          82   16   13   50
4          80    9   10   44

In [12]:
df.describe()

Attendance        MSE        HRS        ESE
count   73.000000  73.000000  73.000000  73.000000
mean    81.698630   9.780822  12.904110  46.630137
std      9.506847   3.047069   5.701278   6.617542
min     62.000000   3.000000   2.000000  32.000000
25%     75.000000   8.000000   8.000000  42.000000
50%     80.000000  10.000000  14.000000  47.000000
75%     90.000000  11.000000  18.000000  50.000000
max     98.000000  17.000000  22.000000  64.000000

In [13]:
endog = df['ESE'].head(4)
exog =  df[['MSE','Attendance','HRS']].head(4)
print(exog)

   MSE  Attendance  HRS
0   10          70   17
1    7          92   20
2    3          67   18
3   16          82   13


In [14]:
x=exog.to_numpy()
y= endog.to_numpy()
print(x)

[[10 70 17]
 [ 7 92 20]
 [ 3 67 18]
 [16 82 13]]


In [15]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [16]:
M = mean(x.T, axis=1)
print(M)

[ 9.   77.75 17.  ]


In [17]:
C= x-M
print(C)

[[  1.    -7.75   0.  ]
 [ -2.    14.25   3.  ]
 [ -6.   -10.75   1.  ]
 [  7.     4.25  -4.  ]]


In [18]:
V = cov(C.T)
print(V)

[[ 30.          19.33333333 -13.33333333]
 [ 19.33333333 132.25         5.        ]
 [-13.33333333   5.           8.66666667]]


In [19]:
values, vectors = eig(V)
print(vectors)
print(values)

[[-0.17721376 -0.86455713  0.47025126]
 [-0.98396696  0.14588088 -0.10260501]
 [-0.02010722  0.48089472  0.87654776]]
[135.8341334   34.15422626   0.928307  ]


In [20]:
P = vectors.T.dot(C.T)
print(P.T)

[[  7.44853019  -1.99513394   1.26544005]
 [-13.72742335   5.25060095   0.22701942]
 [ 11.62082019   4.10001808  -0.84195598]
 [ -5.34192703  -7.35548508  -0.6505035 ]]


In [21]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1'])

In [22]:
exog1 = sm.add_constant(principalDf[['principal component 1']])
print(exog1)

   const  principal component 1
0    1.0              -7.448530
1    1.0              13.727423
2    1.0             -11.620820
3    1.0               5.341927


In [23]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
model = lm.fit(exog1,endog)
lm.coef_

array([0.       , 0.2889832])

In [24]:
lm.intercept_

40.75

In [25]:
def RSE(y_true, y_predicted):
   
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))

    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [26]:
ypred =lm.predict(exog1)

In [27]:
re = RSE(endog,ypred)
print(re)

8.146132476706372
